# Change these first
owner: Jamior # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Homepage
    url: https://jadyn.au
  - name: Portainer
    url: https://portainer.jadyn.au
  - name: Gitlab
    url: https://gitlab.jadyn.au
  - name: Nebula 
    url: https://dashboard.jadyn.au
  - name: Riot 
    url: https://riot.jadyn.au
  - name: Embeds 
    url: https://embed.jadyn.au
  - name: Lynx 
    url: https://i.jadyn.au
  - name: MC Server Creamy
    url: 15.235.216.42
    port: 25573
    check: "tcp-ping"
  - name: Sparked Server
    url: 51.161.198.223
    port: 25501
    check: "tcp-ping"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status-dev.jadyn.au
  theme: dark
  logoUrl: https://github.com/Jamior/status/blob/master/image03.png
  # baseUrl: /your-repo-name
  name: Service Status
  introTitle: "**Jadyn.au**"
  introMessage: Uptime for my services I host.
  navbar:
    - title: Status
      href: /
    - title: Discord
      href: https://discord.gg/AYUPyKQX6b
  metaTags:
    - name: "robots"
      content: "noindex"
  robotsText: "User-agent: * \n Disallow: /"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
